name: adwaita_example
description: Demonstrates Adwaita theming
publish_to: none
version: 4.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  adwaita:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
