name: adwaita
description: Adwaita style - The default theme for GTK+ for your Flutter app.
version: 0.5.0
homepage: https://github.com/gtk-flutter/adwaita

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^2.4.0

flutter:
